#pragma once
#include <cstdint>

namespace GalaxyEggbert {

// Player (Blupi) animation/movement state. Values match original ACTION_* constants
// from the Windows Phone game — do not renumber (used in animation tables).
enum class BlupiAction : uint8_t
{
    None          = 0,
    Stop          = 1,
    March         = 2,
    Turn          = 3,
    Jump          = 4,
    Air           = 5,
    Down          = 6,
    Up            = 7,
    Vertigo       = 8,
    Recede        = 9,
    Advance       = 10,
    Clear1        = 11,
    Set           = 12,
    Win           = 13,
    Push          = 14,
    StopHelico    = 15,
    MarchHelico   = 16,
    TurnHelico    = 17,
    StopNage      = 18,
    MarchNage     = 19,
    TurnNage      = 20,
    StopSurf      = 21,
    MarchSurf     = 22,
    TurnSurf      = 23,
    Drown         = 24,
    StopJeep      = 25,
    MarchJeep     = 26,
    TurnJeep      = 27,
    StopPop       = 28,
    Pop           = 29,
    Bye           = 30,
    StopSuspend   = 31,
    MarchSuspend  = 32,
    TurnSuspend   = 33,
    JumpSuspend   = 34,
    Hide          = 35,
    JumpAie       = 36,
    StopSkate     = 37,
    MarchSkate    = 38,
    TurnSkate     = 39,
    JumpSkate     = 40,
    AirSkate      = 41,
    TakeSkate     = 42,
    DeposeSkate   = 43,
    Ouf1a         = 44,
    Ouf1b         = 45,
    Ouf2          = 46,
    Ouf3          = 47,
    Ouf4          = 48,
    Sucette       = 49,
    StopTank      = 50,
    MarchTank     = 51,
    TurnTank      = 52,
    FireTank      = 53,
    Glu           = 54,
    Drink         = 55,
    Charge        = 56,
    Electro       = 57,
    HelicoGlu     = 58,
    TurnAir       = 59,
    StopMarch     = 60,
    StopJump      = 61,
    StopJumph     = 62,
    Mockery       = 63,
    Mockeryi      = 64,
    Ouf5          = 65,
    Balloon       = 66,
    StopOver      = 67,
    MarchOver     = 68,
    TurnOver      = 69,
    Recedeq       = 70,
    Advanceq      = 71,
    StopEcrase    = 72,
    MarchEcrase   = 73,
    Teleporte     = 74,
    Clear2        = 75,
    Clear3        = 76,
    Clear4        = 77,
    Clear5        = 78,
    Clear6        = 79,
    Clear7        = 80,
    Clear8        = 81,
    Switch        = 82,
    Mockeryp      = 83,
    Non           = 84,
    SlowdownSkate = 85,
    TakeDynamite  = 86,
    PutDynamite   = 87,
};

constexpr uint8_t ToRaw(BlupiAction a) { return static_cast<uint8_t>(a); }
constexpr BlupiAction ToBlupiAction(int v) { return static_cast<BlupiAction>(static_cast<uint8_t>(v)); }

} // namespace GalaxyEggbert
